<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TavosMarket.Application\TavosMarket.Application.csproj" />
      <ProjectReference Include="..\TavosMarket.Infrastructure\TavosMarket.Infrastructure.csproj" />
      <ProjectReference Include="..\TavosMarket.Shared\TavosMarket.Shared.csproj" />
    </ItemGroup>

</Project>
